import type { Metadata } from "next";
import LayoutContainer from "../app/layoutContainer";
import { GlobalContextProvider } from '@/code/globalContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalContextProvider>
      <LayoutContainer>
          {children}
      </LayoutContainer>
    </GlobalContextProvider>
  );
}
